[package]
name = "mount-ctrl"
version = "0.1.1"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2018"
license = "MIT"
description = "Giant Magellan Telescope mount control system"
repository = "https://github.com/rconan/mount-ctrl"
documentation = "https://docs.rs/mount-ctrl"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dosio = {  version = "^0.1.3", default-features = false }
paste = "1.0.5"
simulink-rs = "^0.1.0"

[features]
default = ["pdr", "dosio/default"]
pdr = []
cdr = []
dos-prqt = ["dosio/prqt"]

[build-dependencies]
cc = "1.0.68"

[package.metadata.docs.rs]
no-default-features = true
features = ["pdr", "dos-prqt"]