[package]
name = "mount-ctrl"
version = "0.1.0"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dosio = { git = "https://github.com/rconan/dosio.git", branch = "main" }
paste = "1.0.5"
simulink-rs = { git = "https://github.com/rconan/simulink-rs.git", branch = "main" }

[features]
default = ["pdr"]
pdr = []
cdr = []

[build-dependencies]
cc = "1.0.68"
